//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.dbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int ID { get; set; }
        public string State_registration_plate { get; set; }
        public int Make { get; set; }
        public int Model { get; set; }
        public int Power { get; set; }
        public System.DateTime Last_maintance { get; set; }
        public int Mileage { get; set; }
        public int Color { get; set; }
        public decimal Luxury_coefficient { get; set; }
        public decimal Price_per_hour { get; set; }
        public decimal Price_per_day { get; set; }
    
        public virtual Color Color1 { get; set; }
        public virtual Make_of_car Make_of_car { get; set; }
        public virtual Model_of_car Model_of_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
