//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.dbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentEntities1 : DbContext
    {
        public CarRentEntities1()
            : base("name=CarRentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Car_status> Car_status { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Make_of_car> Make_of_car { get; set; }
        public virtual DbSet<Model_of_car> Model_of_car { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<Rent_type> Rent_type { get; set; }
        public virtual DbSet<Renter> Renter { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
